# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ike < Formula
  desc "k9s-style terminal UI for Datadog — monitors, incidents, SLOs, logs and dashboards with k9s muscle memory"
  homepage "https://github.com/Cesarsk/ike"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cesarsk/ike/releases/download/v0.1.0/ike_0.1.0_darwin_amd64.tar.gz"
      sha256 "72b1af7beef55e9ceaa511a6077bff659024170fe5cd8540ab2a20c99d29dd1b"

      define_method(:install) do
        bin.install "ike"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cesarsk/ike/releases/download/v0.1.0/ike_0.1.0_darwin_arm64.tar.gz"
      sha256 "dfae4ff2698bdcdf2762802a7bf707622a60d7f8c6365c96d70cf019e69e03fd"

      define_method(:install) do
        bin.install "ike"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cesarsk/ike/releases/download/v0.1.0/ike_0.1.0_linux_amd64.tar.gz"
      sha256 "5e258014e4189f7ec75b1bfc267e19e1b99fe2caf53069ad8e09c2ad811b149b"
      define_method(:install) do
        bin.install "ike"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cesarsk/ike/releases/download/v0.1.0/ike_0.1.0_linux_arm64.tar.gz"
      sha256 "c9dbbd223a803b344fbb438f565a30e5f0159480cfa8fe19c694fe111eb522ca"
      define_method(:install) do
        bin.install "ike"
      end
    end
  end

  test do
    assert_match "ike", shell_output("#{bin}/ike --version")
  end
end
