# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ike < Formula
  desc "k9s-style terminal UI for Datadog — monitors, incidents, SLOs, logs and dashboards with k9s muscle memory"
  homepage "https://github.com/Cesarsk/ike"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cesarsk/ike/releases/download/v0.2.1/ike_0.2.1_darwin_amd64.tar.gz"
      sha256 "6209cc386f7ef3e9287fce74ef5342782bd51aaa8416dafe191c8ad1656e3c24"

      define_method(:install) do
        bin.install "ike"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cesarsk/ike/releases/download/v0.2.1/ike_0.2.1_darwin_arm64.tar.gz"
      sha256 "0715f800f3b2b13eca0fa9374f057bf7b741139ef02dc46e86d09918dc579ac5"

      define_method(:install) do
        bin.install "ike"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cesarsk/ike/releases/download/v0.2.1/ike_0.2.1_linux_amd64.tar.gz"
      sha256 "a2b52675ad8ff6d274cbfba7a50dfb33923a0b07c15fc3b0099eb2002043cc1c"
      define_method(:install) do
        bin.install "ike"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cesarsk/ike/releases/download/v0.2.1/ike_0.2.1_linux_arm64.tar.gz"
      sha256 "ee96881387c56ae29b88523243d148b62f2a02e0a62928f51a72aaf9efda1a92"
      define_method(:install) do
        bin.install "ike"
      end
    end
  end

  test do
    assert_match "ike", shell_output("#{bin}/ike --version")
  end
end
